apiVersion: v1
kind: Service
metadata:
  name: demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3005
  selector:
    app: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: registry.simplyeverything.com/demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
      imagePullSecrets:
        - name: regcred
