apiVersion: v1
kind: Service
metadata:
  name: api-demo
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: api-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-demo
  template:
    metadata:
      labels:
        app: api-demo
    spec:
      containers:
        - name: api-demo
          image: registry.simplyeverything.com/api-demo:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: api-demo-config
            - secretRef:
                name: api-demo-secret
      imagePullSecrets:
        - name: regcred
