apiVersion: v1
kind: Service
metadata:
  name: admin
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3005
  selector:
    app: admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: admin
          image: registry.simplyeverything.com/admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3005
      imagePullSecrets:
        - name: regcred
